"""Initial with boards

Revision ID: 03da7b8ffe20
Revises: 
Create Date: 2026-02-26 14:28:36.858464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03da7b8ffe20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_board_creator_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board'))
    )
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_creator_id'), ['creator_id'], unique=False)

    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name=op.f('fk_follows_followed_id_user')),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_follows_follower_id_user')),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('pk_follows'))
    )
    op.create_table('board_collaborators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_board_collaborators_board_id_board')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_board_collaborators_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'board_id', name=op.f('pk_board_collaborators'))
    )
    op.create_table('board_followers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_board_followers_board_id_board')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_board_followers_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'board_id', name=op.f('pk_board_followers'))
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_post_board_id_board')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_post_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_created_at'))
        batch_op.drop_index(batch_op.f('ix_post_board_id'))

    op.drop_table('post')
    op.drop_table('board_followers')
    op.drop_table('board_collaborators')
    op.drop_table('follows')
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_creator_id'))

    op.drop_table('board')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
